window.FIRSTROLL_CONFIG = Object.freeze({
  apiBase: "",
  publicMode: false,
  videoAnalysisEnabled: true,
  authProvider: "supabase",
  supabaseUrl: "",
  supabasePublishableKey: "",
  entraAuthority: "",
  entraSpaClientId: "",
  entraApiScope: "",
  buildId: "v-next",
  buildNumber: 0,
  buildChannel: "local",
  buildCommit: "working-tree",
});
